<a href="https://colab.research.google.com/github/Maradonas/Pos-Tech-ML/blob/main/Aula1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df_excel = pd.read_excel('Chess.xlsx',sheet_name='Chess')

In [8]:
df_csv = pd.read_csv('Tomato.csv',sep=',')

In [9]:
df_csv.head(5)

Date Unit  Minimum  Maximum  Average  Market
0  2013-06-16   Kg       26       32     29.0  Tomato
1  2013-06-17   Kg       20       25     22.5  Tomato
2  2013-06-18   Kg       22       26     24.0  Tomato
3  2013-06-19   Kg       24       28     26.0  Tomato
4  2013-06-20   Kg       22       26     24.0  Tomato

In [11]:
df_excel.head()

rated    created_at  last_move_at  turns victory_status winner  \
20053   True  1.499791e+12  1.499791e+12     24         resign  white   
20054   True  1.499698e+12  1.499699e+12     82           mate  black   
20055   True  1.499698e+12  1.499698e+12     35           mate  white   
20056   True  1.499696e+12  1.499697e+12    109         resign  white   
20057   True  1.499643e+12  1.499644e+12     78           mate  black   

      increment_code      white_id  white_rating            black_id  \
20053          10+10       belcolt          1691            jamboger   
20054           10+0      jamboger          1233  farrukhasomiddinov   
20055           10+0      jamboger          1219        schaaksmurf3   
20056           10+0  marcodisogno          1360            jamboger   
20057           10+0      jamboger          1235               ffbob   

       black_rating opening_eco                     opening_name  opening_ply  
20053          1220         A80                    Dutch Defense            2  
20054          1196         A41                     Queen's Pawn            2  
20055          1286         D00  Queen's Pawn Game: Mason Attack            3  
20056          1227         B07                     Pirc Defense            4  
20057          1339         D00  Queen's Pawn Game: Mason Attack            3

In [12]:
df_csv.tail()

Date Unit  Minimum  Maximum  Average  Market
2736  2021-05-09   Kg       10       15     12.5  Tomato
2737  2021-05-10   Kg       10       15     12.5  Tomato
2738  2021-05-11   Kg       10       15     12.5  Tomato
2739  2021-05-12   Kg       30       35     32.5  Tomato
2740  2021-05-13   Kg       35       40     37.5  Tomato

In [19]:
df_csv.shape

(2741, 6)

In [21]:
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20058 entries, 0 to 20057
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   rated           20058 non-null  bool   
 1   created_at      20058 non-null  float64
 2   last_move_at    20058 non-null  float64
 3   turns           20058 non-null  int64  
 4   victory_status  20058 non-null  object 
 5   winner          20058 non-null  object 
 6   increment_code  20058 non-null  object 
 7   white_id        20058 non-null  object 
 8   white_rating    20058 non-null  int64  
 9   black_id        20058 non-null  object 
 10  black_rating    20058 non-null  int64  
 11  opening_eco     20058 non-null  object 
 12  opening_name    20058 non-null  object 
 13  opening_ply     20058 non-null  int64  
dtypes: bool(1), float64(2), int64(4), object(7)
memory usage: 2.0+ MB


In [23]:
df_csv.describe().T

count       mean        std   min   25%   50%   75%    max
Minimum  2741.0  35.089748  16.648425   8.0  22.0  30.0  45.0  115.0
Maximum  2741.0  41.281284  17.364135  12.0  30.0  38.0  50.0  120.0
Average  2741.0  38.185516  16.970949  10.0  25.0  35.0  47.5  117.5

In [24]:
df_excel.head()

rated    created_at  last_move_at  turns victory_status winner  \
0  False  1.504210e+17  1.504210e+17     13      outoftime  white   
1   True  1.504130e+17  1.504130e+17     16         resign  black   
2   True  1.504130e+17  1.504130e+17     61           mate  white   
3   True  1.504110e+17  1.504110e+17     61           mate  white   
4   True  1.504030e+17  1.504030e+17     95           mate  white   

  increment_code       white_id  white_rating      black_id  black_rating  \
0           15+2       bourgris          1500          a-00          1191   
1           5+10           a-00          1322     skinnerua          1261   
2           5+10         ischia          1496          a-00          1500   
3           20+0  daniamurashov          1439  adivanov2009          1454   
4           30+3      nik221107          1523  adivanov2009          1469   

  opening_eco                            opening_name  opening_ply  
0         D10        Slav Defense: Exchange Variation            5  
1         B00  Nimzowitsch Defense: Kennedy Variation            4  
2         C20   King's Pawn Game: Leonardis Variation            3  
3         D02  Queen's Pawn Game: Zukertort Variation            3  
4         C41                        Philidor Defense            5

In [25]:
set(df_excel['victory_status'])

{'draw', 'mate', 'outoftime', 'resign'}

In [26]:
df_csv.head()

Date Unit  Minimum  Maximum  Average  Market
0  2013-06-16   Kg       26       32     29.0  Tomato
1  2013-06-17   Kg       20       25     22.5  Tomato
2  2013-06-18   Kg       22       26     24.0  Tomato
3  2013-06-19   Kg       24       28     26.0  Tomato
4  2013-06-20   Kg       22       26     24.0  Tomato

In [27]:
set(df_csv['Market'])

{'Tomato'}

In [28]:
df_csv.describe()

Minimum      Maximum      Average
count  2741.000000  2741.000000  2741.000000
mean     35.089748    41.281284    38.185516
std      16.648425    17.364135    16.970949
min       8.000000    12.000000    10.000000
25%      22.000000    30.000000    25.000000
50%      30.000000    38.000000    35.000000
75%      45.000000    50.000000    47.500000
max     115.000000   120.000000   117.500000

In [35]:
def categorizar_tomate_media(media):
  if media >= 40 and media<=70:
    return "Tomate medio"
  elif media < 40:
    return "Tomate pequeno"
  else:
    return "Tomatão"

In [36]:
df_csv['categoria_tomate'] = df_csv['Average'].apply(categorizar_tomate_media)

In [37]:
df_csv.head(2)

Date Unit  Minimum  Maximum  Average  Market categoria_tomate
0  2013-06-16   Kg       26       32     29.0  Tomato   Tomate pequeno
1  2013-06-17   Kg       20       25     22.5  Tomato   Tomate pequeno

In [40]:
df_csv.groupby(['categoria_tomate']).describe()

Minimum                                                      \
                   count       mean       std   min   25%   50%   75%    max   
categoria_tomate                                                               
Tomate medio       954.0  47.818658  8.203065  30.0  40.0  45.0  55.0   65.0   
Tomate pequeno    1638.0  23.978022  7.175572   8.0  18.0  25.0  30.0   38.0   
Tomatão            149.0  75.744966  7.324666  65.0  70.0  75.0  80.0  115.0   

                 Maximum             ...              Average             \
                   count       mean  ...   75%    max   count       mean   
categoria_tomate                     ...                                   
Tomate medio       954.0  55.009434  ...  60.0   75.0   954.0  51.414046   
Tomate pequeno    1638.0  29.528694  ...  35.0   44.0  1638.0  26.753358   
Tomatão            149.0  82.583893  ...  85.0  120.0   149.0  79.164430   

                                                           
                       std   min   25%   50%   75%    max  
categoria_tomate                                           
Tomate medio      8.272792  40.0  45.0  50.0  57.5   70.0  
Tomate pequeno    7.191735  10.0  21.5  27.5  32.5   39.5  
Tomatão           7.367396  70.5  75.0  77.5  82.5  117.5  

[3 rows x 24 columns]

In [45]:
filtro = df_csv["Average"]<40

In [46]:
df_csv.loc[filtro]

Date Unit  Minimum  Maximum  Average  Market categoria_tomate
0     2013-06-16   Kg       26       32     29.0  Tomato   Tomate pequeno
1     2013-06-17   Kg       20       25     22.5  Tomato   Tomate pequeno
2     2013-06-18   Kg       22       26     24.0  Tomato   Tomate pequeno
3     2013-06-19   Kg       24       28     26.0  Tomato   Tomate pequeno
4     2013-06-20   Kg       22       26     24.0  Tomato   Tomate pequeno
...          ...  ...      ...      ...      ...     ...              ...
2736  2021-05-09   Kg       10       15     12.5  Tomato   Tomate pequeno
2737  2021-05-10   Kg       10       15     12.5  Tomato   Tomate pequeno
2738  2021-05-11   Kg       10       15     12.5  Tomato   Tomate pequeno
2739  2021-05-12   Kg       30       35     32.5  Tomato   Tomate pequeno
2740  2021-05-13   Kg       35       40     37.5  Tomato   Tomate pequeno

[1638 rows x 7 columns]

Numpy

In [48]:
arr_list = np.array([1,2,3,4,5,6,7,8])

In [51]:
arr_list

array([1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
arr_zeros = np.ones((4,6))

In [62]:
arr_zeros

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [126]:
arr_randon = np.random.rand(3,4)
arr_randon

array([[0.81046011, 0.10440772, 0.6223118 , 0.74455308],
       [0.64868623, 0.14706087, 0.94760438, 0.37948678],
       [0.1437393 , 0.96206499, 0.42575357, 0.61798765]])

In [127]:
arr_randon.shape

(3, 4)

In [139]:
arry_random_reshape = arr_randon.reshape((4,3))

In [137]:
arry_random_reshape

array([[0.81046011, 0.10440772, 0.6223118 ],
       [0.74455308, 0.64868623, 0.14706087],
       [0.94760438, 0.37948678, 0.1437393 ],
       [0.96206499, 0.42575357, 0.61798765]])

In [132]:
arry_random_reshape.shape

(4, 3)

In [148]:
arr1 = np.array([ [1,2]
                 ,[3,4]])

In [152]:
arr2 = np.array([[5,6]
                ,[7,8]])

In [153]:
arr3 = np.array([[9,10]
                 ,[11,12]])

In [162]:
arr4 = np.concatenate((arr1,arr2,arr3),axis=1)

In [163]:
arr4

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

In [167]:
arr4_split = np.split(arr4,2)

In [171]:
arry4_transpose = np.transpose(arr4)

In [172]:
arry4_transpose

array([[ 1,  3],
       [ 2,  4],
       [ 5,  7],
       [ 6,  8],
       [ 9, 11],
       [10, 12]])

In [178]:
arr4_revertido = arry4_transpose.T
arr4_revertido

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

In [181]:
arr_a   = np.array([1, 7, 27])
arr_b   = np.array([1, 5, 1])

In [185]:
arr_a_b = np.add(arr_a,arr_b)
#arr_a_b = arr_a + arr_b

In [186]:
arr_a_b

array([ 2, 12, 28])

In [187]:
arr_sub_a_b = np.subtract(arr_a,arr_b)

In [188]:
arr_sub_a_b

array([ 0,  2, 26])